---
- name: Copy mysql.pam to /etc/pam.d/mysql 
  become: true
  file:
    src: mysql.pam
    dest: /etc/pam.d/mysql
    owner: root
    group: root
    mode: 0644
    state: present

- name: Copy my.cnf global MySQL configuration
  become: true
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql
  
- meta: flush_handlers

- name: Ensure mariadb service is started and enabled
  become: true
  service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: true
