---
# handlers file for jhu_mysql
- name: restart mysql
  become: true
  service: "name={{ mysql_daemon }} state=restarted sleep=5"

- name: create systemd tmpfiles
  become: true
  command: /usr/bin/systemd-tmpfiles --create